
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Product extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ex = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/WhatsApp Image 2022-09-24 at 11.26.02 AM.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ProductID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 45, 80, 15);
        getContentPane().add(id);
        id.setBounds(122, 42, 63, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ProductName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 80, 15);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(122, 80, 63, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Category");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(33, 121, 70, 15);
        getContentPane().add(category);
        category.setBounds(122, 118, 63, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Price of item");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(33, 162, 90, 15);
        getContentPane().add(price);
        price.setBounds(125, 159, 60, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Pro.date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(227, 45, 50, 14);

        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        getContentPane().add(pro);
        pro.setBounds(283, 42, 90, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Ex.date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(227, 83, 60, 14);
        getContentPane().add(ex);
        ex.setBounds(283, 80, 90, 25);

        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 230, 40, 21);

        jButton2.setText("Update");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(110, 230, 70, 21);

        jButton3.setText("Delete");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 230, 80, 21);

        jButton4.setText("cancel");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(930, 400, 70, 21);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(524, 60, 452, 160);

        jButton5.setText("Search");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(350, 230, 73, 21);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(227, 123, 49, 14);
        getContentPane().add(quantity);
        quantity.setBounds(294, 118, 79, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/f8d7f5c462a713a9d55767e409b20974.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 4, 1080, 470);

        setSize(new java.awt.Dimension(1076, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
          String sql="INSERT INTO product "
                  +"(ProductID,ProductName,Category,Price,ProDate,ExDate,Quantity)"
                  +"VALUES (?,?,?,?,?,?,?)";
          con =DriverManager.getConnection("jdbc:mysql://localhost:3306/ghandour","root","");
          pst = con.prepareStatement(sql);
          pst.setString(1,id.getText());
          pst.setString(2,name.getText());
            pst.setString(3,category.getText());
             pst.setString(4,price.getText()); 
             pst.setString(5,pro.getText());
              pst.setString(6,ex.getText());
               pst.setString(7,quantity.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null," inserted successfully");
      }
      catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
      }showTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try{
          String sql="DELETE FROM product WHERE ProductID=?";
          con =DriverManager.getConnection("jdbc:mysql://localhost:3306/ghandour","root","");
          pst = con.prepareStatement(sql);
          pst.setString(1,id.getText());
          pst.executeUpdate();
             JOptionPane.showMessageDialog(null," delete successfully");
      }
      catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
      }showTableData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           try{
          String sql="UPDATE product SET ProductName=?,Category=?,Price=?,ProDate=?,ExDate=?,Quantity=? WHERE ProductID=?";
          con =DriverManager.getConnection("jdbc:mysql://localhost:3306/ghandour","root","");
          pst = con.prepareStatement(sql);
          pst.setString(7,id.getText());
          pst.setString(1,name.getText());
            pst.setString(2,category.getText());
             pst.setString(3,price.getText()); 
             pst.setString(4,pro.getText());
              pst.setString(5,ex.getText());
              pst.setString(6,quantity.getText());
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null," updated successfully");
      }
      catch(HeadlessException | SQLException ex){
           JOptionPane.showMessageDialog(null,ex);
      }showTableData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
             try {
               
                 pst=con.prepareStatement("SELECT ProductID, ProductName, Category, Price, ProDate, ExDate,Quantity FROM product WHERE ProductID=?");
            
      
          
           
           int ID = Integer.parseInt(id.getText());
           pst.setInt(1, ID);
           ResultSet rs = pst.executeQuery();
           if(rs.next()==false)
           {
               JOptionPane.showMessageDialog(this," not found");
               name.setText("");
               category.setText("");
               price.setText("");
               pro.setText("");
               ex.setText("");
               quantity.setText("");
           }
           else
           {
               name.setText(rs.getString("ProductName"));
               category.setText(rs.getString("Category"));
               price.setText(rs.getString("Price"));
               pro.setText(rs.getString("ProDate"));
               ex.setText(rs.getString("ExDate"));
               quantity.setText(rs.getString("Quantity"));
               
           }
          String name1=name.getText();
          String category1=category.getText();
          String price1=price.getText();
          String pro1=pro.getText();
          String ex1=ex.getText();
          String quantity1=quantity.getText();
          
          DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
          model.setRowCount(0);
            model.addRow(new String[]{Integer.toString(ID),name1,category1,price1,pro1,ex1,quantity1});
            
            
               
             } 
          
             catch (SQLException ex) {
            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton5ActionPerformed
public void showTableData(){
    try{ //int id1=Integer.parseInt(id.getText());
        con =DriverManager.getConnection("jdbc:mysql://localhost:3306/ghandour","root","");
        String sql = "select * from product";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
       // DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       // model.setRowCount(0);
       /* while(rs.next()){
            model.addRow(new String[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)});
        }*/
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField category;
    private javax.swing.JTextField ex;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField pro;
    private javax.swing.JTextField quantity;
    // End of variables declaration//GEN-END:variables
}
